### ISSUE TITLE
不具合？

### ISSUE THREAD

**Issue by sasa2121** [TORISOUP/GTAV_InfernoScripts#11]
インフェルノＭＯＤをreadmeの内容の様に導入してみたのですが、ScriptHookVDotNet.logで読み込めない不具合？が出たので確認お願いします。
スペックはWindows７　CPU Intel corei7  メモリは８ＧＢ グラボはＧＴＸ７６０です。
現在ＭＯＤはScriptHookV、ScriptHookVDotNet、インフェルノＭＯＤのみ導入しています。
ScriptHookVDotNet.logで出力した物を以下に記します。
22:50:38] [ERROR] Failed to load assembly 'Inferno.dll':
System.IO.FileLoadException: ファイルまたはアセンブリ 'Inferno.DLL'、またはその依存関係の 1 つが読み込めませんでした。アクセスが拒否されました。
ファイル名 'Inferno.DLL' です。'Inferno.DLL'
   場所 System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   場所 System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   場所 System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   場所 System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   場所 System.Reflection.Assembly.LoadFrom(String assemblyFile)
   場所 GTA.ScriptDomain.LoadAssembly(String filename)

[22:50:38] [DEBUG] Found 0 script(s) in 'ReactiveProperty.dll'.
[22:50:38] [DEBUG] Found 0 script(s) in 'System.Reactive.Core.dll'.
[22:50:38] [DEBUG] Found 0 script(s) in 'System.Reactive.Interfaces.dll'.
[22:50:38] [DEBUG] Found 0 script(s) in 'System.Reactive.Linq.dll'.
[22:50:38] [DEBUG] Found 0 script(s) in 'System.Reactive.PlatformServices.dll'.

**Comment by meronmks** [comment]
お手数ですがInferno.dllを右クリックしてプロパティを表示していただき「ブロックの解除」という項目が存在するか確認できますかね？
もし存在したらクリックしてもらえると動く可能性があります。

**Comment by sasa2121** [comment]
回答ありがとうございます
ご指摘通りにブロックの解除をしてみましたがはInferno.dllは変わらず動きませんでした。
ワクチンソフトの誤検知かと思ってソフトを切ってみましたが変わらずでした…

**Comment by TORISOUP** [comment]
エラーの内容から察するに、ScriptHookVDotNetがInfernoMODを起動しようとしたけどアクセス拒否されて起動できなかったって感じですかねぇ。環境依存の問題っぽいのでInfernoMODを修正してどうこうなる問題じゃなさそうかと。

対応としては、Inferno.dllが破損している可能性もあるので、再DLして試してみる。GTAVを起動する際に管理者権限で起動する。とかですかね。
ちなみにGTAVのディレクトリ構成ってどうなってます？

**Comment by sasa2121** [comment]
ＧＴＡの管理者権限は機能してくれませんでした。今いろいろ再ダウンロード中です…
x64a.rpf～x64ｗ.rpfまで少しカットしましたが、ディレクトリ構成って下記であってますか？
E:\SteamLibrary\steamapps\common\Grand Theft Auto V
│  asiloader.log
│  bink2w64.dll
│  common.rpf
│  d3dcompiler_46.dll
│  d3dcsx_46.dll
│  dinput8.dll
│  GFSDK_ShadowLib.win64.dll
│  GFSDK_TXAA.win64.dll
│  GFSDK_TXAA_AlphaResolve.win64.dll
│  GTA5.exe
│  GTAVLauncher.exe
│  installscript.vdf
│  LUA.asi
│  NativeTrainer.asi
│  scripthookv.dll
│  ScriptHookV.log
│  ScriptHookVDotNet.asi
│  ScriptHookVDotNet.dll
│  ScriptHookVDotNet.log
│  steam_api64.dll
│  steam_appid.txt
│  x64a.rpf
～～～～～～～～～～～～～
│  x64w.rpf
│  
├─Installers
│      Social Club v1.1.6.0 Setup.exe
│  
├─scripts
│  │  Inferno.dll
│  │  ReactiveProperty.dll
│  │  System.Reactive.Core.dll
│  │  System.Reactive.Interfaces.dll
│  │  System.Reactive.Linq.dll
│  │  System.Reactive.PlatformServices.dll
│  │  
│  ├─chaosmode
│  │      default.conf
│  │  
│  └─Pichun
├─update
│  │  update.rpf
│  │  
│  └─x64

**Comment by meronmks** [comment]
LUA.asiは.Net系と相性が悪いみたいでMODが起動しないなどがあるみたいなので一度外してみてもらえますかね？

**Comment by sasa2121** [comment]
再ダウンロードを済ませてLUA.asiを入れずにやってみたら、インフェルノＭＯＤが機能しました。
ありがとうございます。
投稿が遅くなってしまったことと、お騒がせしてすいませんでした。

**Comment by meronmks** [comment]
無事に動作したようで良かったです
