### ISSUE TITLE
導入方法について

### ISSUE THREAD

**Issue by TORISOUP** [TORISOUP/GTAV_InfernoScripts#13]

**Comment by kamikami333** [comment]
TORISOUP様の誘導でこちらへ来ました。

すみません質問させて下さい。
GTA5のインフェルノ動画を見て、これは面白そう！と思いReadmeを見ながら
導入しょうとしましたが、途中でつまづきいました。
ReactiveExtensions 2.2.5及びReactiveProperty 2.2のファイルネームが
いまいち分かりません・・・・・OTL
それと上記2つのファイルネームをRxInstallerファルダの中に入れればいいのでしょうか？
よろしくお願いいたします。

**Comment by TORISOUP** [comment]
[こちらのexeファイル](https://nuget.org/nuget.exe)をRxInstaller.batと同じフォルダにDLして配置してください。
その後にRxInstaller.batを実行すれば必要なファイルが生成されるはずです。

**Comment by kamikami333** [comment]
無事導入が完了出来ました。
どうもありがとうございました。
