### ISSUE TITLE
カオスモード上で遭遇した不具合について

### ISSUE THREAD

**Issue by aotori** [TORISOUP/GTAV_InfernoScripts#14]
初めまして、とりすーぷ様の制作されたmod「カオスモードMOD」を勝手に楽しませて頂いている者です。
いつもありがとうございます。

さて、本日はこの前発見した不具合についての報告の為、こちらにご連絡させていただきました。
まず、症状について簡単に説明させて頂きます。
カオスモードをONの状態で(インフェルノモードはOFFの状態)GTAVをプレイしている最中、
特定の地域に行くとゲームのみがクラッシュし(PCごと落ちるわけではない)、
ゲームの再起動を余儀なくされるというものです。

詳細は以下の方に記しておきました。
この症状が当方PCのスペック不足に因るものか、それともプログラム上の欠陥に因るのもなのか
知りたく思い連絡致しました。
もしよろしければ、回答を頂けると幸いです。

【PCスペック】
OS
→Windows 7 Pro
CPU
→Corei7-3770K
GPU
→GTX 670
RAM
→16GB
SSD
→120GB×2
(片方がCドライブ)
HHD
→1TB×1, 2TB×2
(2TBの方にGTAVファイル有)

【利用しているMod】
･InfernoMod
･ScriptHookV_1.0.372.2
(http://sunrisegta5.wix.com/grandtheftauto-5-mod#!Script-Hook-V)
･ScriptHookVDotNet
(https://github.com/crosire/scripthookvdotnet/releases)
･the red house
(http://gtavphoto.blog.jp/archives/31639790.html)

【症状の詳細】

カオスモードON(インフェルノモードはOFF)の状態でマップの中央部分、グランド･セノーラ砂漠寄りの
バインウッドヒルズ(丘陵地帯)にて邪知暴虐をしていた所、GTAVのメモリ使用量が2GBを越えた辺りで、
前兆も無くフリーズしゲームがクラッシュする症状に遭遇しました。
偶然性に起因するエラーかと考え繰り返し何度かカオスモードONの状態で上記の地域に向かいましたが、
やはりメモリ使用量が2GBを越えた辺りで同様の症状に陥りました。(キャラは全てフランクリン)
PCのスペック不足を疑い下記の検証を行ったのですが、PCのスペック不足とは考えられない結果となり、
自力での原因解明は不可能と判断した次第です。
尚、検証時に使用したキャラは全てフランクリンです。
また、全ての検証において、タスクマのプロセスタブが示すGTAVのCPUの値はおよそ40前後でした。

「検証①」

PCのスペック不足を疑い、丘陵地帯よりPCへの負荷がより強いであろうマップ下部の市街地で
カオスモードをONにし阿鼻叫喚の地獄絵図を10分以上繰り広げましたが、
メモリ使用量が2.6GBを超えても安定してゲームは動作しておりました。
その後、上記の丘陵地帯へ移動した所、やはりゲームがクラッシュしました。

「検証②」

次にゲームのプログラム自体を疑い、カオスモードOFFの状態で丘陵地帯へ向かいました。
丘陵地帯にて戦車でキリングフィールドを繰り広げ、メモリ使用量も2.6GBを超えましたが、
クラッシュは発生しませんでした。
その後カオスモードをONにした所、しばらく経った頃にクラッシュしました。
(メモリ使用量はクラッシュ時点でおよそ2.6GBでした)

「検証③」
the red houseを一度GTAVシステムファイルから削除して、カオスモードを起動した所、
やはり丘陵地帯でゲームがクラッシュしました。

「検証④」

クラッシュ後に表示される案内に従ってセーフモードで起動した状態で、カオスモードをONにし
丘陵地帯に向かった所、やはりクラッシュしました。
GTX670は確かに数年前のGPUではございますが、それでもセーフモードでクラッシュするのは
おかしいと考え、この検証が終わった時点でカオスモードのプログラムに原因があるのではと
考え始めた次第です。

以上、当方が直面している状況及び行った検証です。
素人目ではございますがPCスペック以外にも原因があると考えており、とりすーぷ様のご意見を
伺いたく存じます。
もしよろしければ、ご回答くださると幸いです。

ここまで読んでくださりありがとうございました。
長文失礼いたしましたm(_ _)m

**Comment by TORISOUP** [comment]
すごい！詳細な情報ありがとうございます！調査します！

**Comment by aotori** [comment]
いえいえこちらこそ色々ありがとうございます、よろしくお願い致します…！！

**Comment by TORISOUP** [comment]
今試してみたところ、自分の環境では特に問題なく動いていました。
前から人気が少ない場所だと落ちやすいとの報告があったので、ひょっとしたら動物に武器をもたせてるのがまずいのかなとも思ったのですが、関係なさそうでした。

以前配布した時と比べていろいろいじっているので、それで安定したのかもしれません。
そろそろ次のバージョンを公開するので、そちらでまた試して頂けないでしょうか？

**Comment by aotori** [comment]
(あ、最初にHDDをHHDって書いちゃってる…恥ずかしい…。)

ご回答ありがとうございます。
なるほど、次に配布されるバージョンでは改善されている可能性があるのですね…。

承知致しました。では新バージョンが配布され次第、症状が改善したか否かについて試してみようと思います。
その後どのような結果になったかについては、またこちらに申し上げに参ります。

**Comment by TORISOUP** [comment]
先ほどβ0.2を公開しました！よろしくお願いします。
http://torisoup.net/gtav/InfernoMOD.zip

**Comment by aotori** [comment]
早い！

ありがとうございます、早速試させていただきますm(_ _)m
