### ISSUE TITLE
緊急脱出とニトロがうまく動作しない

### ISSUE THREAD

**Issue by ghost** [TORISOUP/GTAV_InfernoScripts#15]
始めまして。とりすーぷ様の制作されたMODを使用させていただいており、非常に楽しんでおります。
しかし、ニトロと緊急脱出コマンドがうまく機能しません。
最初はMODの競合や導入ミスを疑ったのですが変化ありませんでした。
もしかしてキーボードでは使用できないのでしょうか？

「cnitro」コマンドを利用すると市民がニトロを使い出すのでニトロシステム自体はうまく動いているはずなのですが・・。
また、緊急脱出も「クラクション」＋「降車」ではなく「Ctrl」＋「降車」で緊急脱出が可能でした。
デフォルトから設定は変えていないはずなんですが・・。

大変ぶしつけな質問となってしまい申し訳ありませんが、よろしくお願いいたします。

**Comment by TORISOUP** [comment]
すいません、そのあたりはゲームパッドの入力値を基準に設定しているので、キーボード操作だとずれている可能性があります。
β0.2をそろそろリリースする予定で、そちらで判定方法をちょっと変えているのでそちらリリース後にもう一度試して頂けないでしょうか

**Comment by ghost** [comment]
ゲームパッド基準だったんですね。お手数おかけして申し訳ありません。
気長に待っています！素早い回答ありがとうございます。

**Comment by kagikn** [comment]
補足させてもらいますと、β0.1の時点では乗車中に使用する緊急脱出やプレイヤーのニトロも(コントローラー設定で)歩行時のキーを基準に判定していたので、ゲームパッドだと正常に動くものの、キーボードだと意図しないキーで発動するようになっていました。
現在の開発版では乗車時のキーで判定するようにして、キーボードでも正常に動くようになったので、次のリリース版で正常に動くようになると思われます。

**Comment by ghost** [comment]
β0.2使用したら使えました！返信遅れて申し訳ありません。

ただ、GTA5が応答無しで落ちるようになったのは・・関係ないと思いますが・・
