### ISSUE TITLE
カオスMODの処理の件

### ISSUE THREAD

**Issue by meronmks** [TORISOUP/GTAV_InfernoScripts#4]
現状のカオスMODの処理ですがこうなってます。
1.武器の取得&交換処理は500msごと、ただし武器リロード中の市民を除く（SMGなのにRPG弾頭詰める荒業が見れるがバグが怖いので）
2.攻撃命令は1000msごとに武器のリロードをしてなければ更新するようになってます
3.攻撃対象は現在攻撃者以外全員（動物も含む）になってます
4.射撃パターンはフルオート、現状ドライブバイはしてきてないはずです
5.市民が死んでも武器を離さない
6.動物も武器によっては射撃する可能性あり

**Comment by TORISOUP** [comment]
概ね良いかと思います。
ただ1秒おきに攻撃命令は細かすぎる気もします。もう少し長くするとどうなりますでしょうか？

**Comment by TORISOUP** [comment]
設定ファイルを読み込ませて、設定を変更できるようにしたい。最初は読み込んで適用するのみ。ゲーム中で編集できるようにする機能は後回し。

設定ファイルで編集できる項目は以下でどうでしょうか？
- Radius: カオス化対象市民の取得半径(m)
- Interval:カオス化間隔 (実行間隔 ms)
- ChaosRatio: カオス化率（0～100%)
- IsChangeMissonCharacterWeapon: ミッションキャラの武器を挿し替えるか ( bool)
- IsChaosMissionCharacter:キャラカオス （0:しない、1:全員カオス化する、2:モブキャラのみカオス化する)
- PlayerCorrection:プレイヤへの攻撃補正 ( false:ランダム,true:補正する)
- PlayerCorrectionProbability:プレイヤの攻撃率（ PlayerCorrection=trueの時のみ有効 0～100%)
- WeaponList:武器一覧

**Comment by meronmks** [comment]
設定の項目数は良いと思います。もしまだ足りないと感じたら後で追加する感じで。
設定ファイルの形式としては4と同じxmlはどうでしょう？

**Comment by TORISOUP** [comment]
xmlは煩雑なのでjsonにしたいなぁと思う所。まぁLINQ to XML使えば大した事はないんですが。

**Comment by TORISOUP** [comment]
あと設定項目にこれが追加できそう
- IsStupidShooting: 射撃の仕方。trueだと棒立ちで撃ちまくる。falseはAIに戦闘処理を委ねる。

**Comment by meronmks** [comment]
確かにjsonの方が良いかもですね
この辺りはライブラリ等の使い易さも含めて考えた方が良さそうですな
あとこの項目も設定に追加できそうです。
・WeaponAccuracy:市民の射撃精度。(0〜100% -1でデフォルトに)

**Comment by TORISOUP** [comment]
jsonもxmlも.NETが元から対応してるんで特に考える必要はないですねぇ

**Comment by meronmks** [comment]
となると見やすさを考えてjsonの方が良いですかもですな

**Comment by meronmks** [comment]
市民の攻撃パターン(棒立ち連射と自分で考えて行動)を割合で混ぜたらいい感じにならないですかな？

**Comment by kamikami333** [comment]
すみません質問させて下さい。
GTA5のインフェルノ動画を見て、これは面白そう！と思いReadmeを見ながら
導入しょうとしましたが、途中でつまづきいました。
ReactiveExtensions 2.2.5及びReactiveProperty 2.2のファイルネームが
いまいち分かりません・・・・・OTL
それと上記2つのファイルネームをRxInstallerファルダの中に入れればいいのでしょうか？
よろしくお願いいたします。

**Comment by TORISOUP** [comment]
新しくIssueを立てて下さい

**Comment by TORISOUP** [comment]
https://github.com/TORISOUP/GTAV_InfernoScripts/issues/13

こちらに書いて頂けると！ @kamikami333

**Comment by kamikami333** [comment]
TORISOUP 様へ
分かりました、すみません。
誘導先の方で導入方法の質問をさせていただきました。
